RMI-PACTA/workflow.aggregate.loanbooks

- README.md
- run_aggregate_loanbooks.R
depends on https://github.com/RMI-PACTA/pacta.supervisor.analysis/pull/57
the R package used to calculate the alignment aggregation is renamed from `pacta.supervisor.analysis` to `pacta.aggregate.loanbook.plots`, hence all references to that package are updated in this workflow
> use renamed aggregation package

- run_aggregate_loanbooks.R
depends on https://github.com/RMI-PACTA/pacta.aggregate.loanbook.plots/pull/62
remove obsolete argument from function call
> rm obsolete arg from function call of sda aggregation

- README.md
- example.env
- run_aggregate_loanbooks.R
depends on https://github.com/RMI-PACTA/pacta.aggregate.loanbook.plots/pull/77
This PR:
- adds `time_frame` as a param to the `example.env` file
- calls arg `time_frame` explicitly in the main workflow
> Use time frame

- run_aggregate_loanbooks.R
- run_pacta_in_bulk.R
relates to #14 
This PR:
- starts splitting the different parts of the workflow in separate manageable scripts, focusing on the part that returns pacta output files and plots in bulk for each `group_id`
- Note: at the moment, this means the loan book preparation is being duplicated, which will be separated out into a dedicated script in a follow up PR
- adds and fixes the function `generate_individual_outputs()` which was previously imported from `pacta.aggregate.loanbook.plots`
- add some checks to ensure `generate_individual_outputs()` is only run when it can be applied appropriately for each `group_id`
> Add script bulk pacta

- prep_input_loanbooks.R
- run_aggregate_loanbooks.R
- run_pacta_in_bulk.R
closes #14 
This PR:
- splits out the preparation of the raw loan books into a dedicated script `prep_input_loanbooks.R`
- explicitly differentiate between `matched_loanbook` and `matched_prioritized`
> Split loanbook scripts

- run_aggregate_loanbooks.R
we need to ensure that subdirectories for all available groups are created in the aggregate result folder before trying to save graphs in that directory. Otherwise the script will not be able to access the path when writing and error out
> ensure subdirectories for each group exist in aggregate results

- run_calculate_coverage.R
relates to ADO https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/7083
This PR:
- adds a workflow that can be used to calculate the coverage of the production data (ABCD) relative to a scenario-based total benchmark
- The ABCD format must be PACTA for banks and the scenario values must be absolute values based on the intermediate scenario data preparation as created in `pacta.scenario.preparation`
- currently this workflow expects a project to be set up in line with the main aggregate analysis of this repository
> calculate production coverage against scenario benchmark

- run_aggregate_loanbooks.R
supersedes #24 
depends on https://github.com/RMI-PACTA/pacta.aggregate.loanbook.plots/pull/82
This PR:
- adapts the generation of the matched loan book to the updated version that returns a matched loan book already
> use new logic of create_benchmark

- run_aggregate_loanbooks.R
If ABCD contains years < start year of the SDA scenarios, the SDA result will have entries for such years. This leads to problems in the sankey plot which uses the first available year + 5. However, the first useful result (correctly) starts in t = start_year for the SDA results. Any rows before the start year are therefore removed before the creation of plots.
> ensure the SDA results have no values smaller than start year

- run_pacta_in_bulk.R
this removes warnings that are related to previously not using `dplyr::all_of()` when selecting multiple columns via a character vector
> get rid of warning related to col_select

- R/functions_prep_project.R
- README.md
- prep_sector_split.R
closes #41 
This PR:
- returns sector spit values for all available companies rather than just for a selected sample of companies.
- the sample of company ids is now restricted to calculating the primary energy based sector split, not the generic equal weights and worst case sector splits
- This allows inner_joining the sector split on the matched loan book without removing company coverage while providing valid sector split values for all companies
- The sector split function also throws a warning if the split introduces a change in coverage of the number of companies in the matched loan book
> Sector split all companies

- prep_sector_split.R
This PR:
- ensures the preparation of the sector split filters companies based on the same logic used in the the run_* scripts to avoid removing companies by accident
> prep_sector_split follows logic used in analysis

- example.env
- prep_input_loanbooks.R
This PR:
- ensure the internally-used script `prep_input_loanbooks.R` does not accidentally return matched loanbooks both on the `direct_loantaker` and the `ultimate_parent` levels, which would artificially duplicate the exposure covered
> ensure prepared loan books are not duplicated

- R/functions_prep_project.R
- prep_sector_split.R
This PR:
- ensures that the function remove_inactive_companies() additionally removes company_sector combinations from the abcd that have a sum of 0 production over the given timeframe
- previously it only removed combinations that start with a positive value and end on zero production (so a company leaving a sector)
- the new addition is helpful to keep only companies from the advanced company indicators that are also given in the P4B abcd.
- advanced company indicators are e.g. used to determine company lists when creating the sector split.
- It therefore ensures that no companies are considered "lost" that could not be matched to the P4B abcd in the first place.
> remove_inactive_companies additionally removes cases of zero total production

- README.md
- example.env
- prep_input_loanbooks.R
- prep_sample_loanbook_raw.R
- run_aggregate_loanbooks.R
- run_calculate_coverage.R
- run_calculate_loanbook_coverage.R
- run_pacta_in_bulk.R
this PR removes the need to load region isos mappers for current scenarios, as these are now all included in the latest r2dii.data releases available on CRAN
> remove reliance on region helper files in favor of r2dii.data::region_isos

- run_calculate_loanbook_coverage.R
update loaded parameters in `run_calculate_loanbook_coverage.R`
I think it must have been a while since I checked this script, it was not functional anymore using the standard parameters described in the README. this change will fix that
> adapt loan book coverage script to run with given params

- R/plots.R
- plot_aggregate_loanbooks.R
To provide an additional overview chart for an ongoing project, we want to display the net aggregate alignment metric by financial exposure at the sector level and by categories, such as the name of the loan book or the type of bank.
Thus, `workflow.aggregate.loanbooks`...
- gains functions `prep_scatter_alignment_exposure` and `plot_scatter_alignment_exposure`, both stored in R/plots.R
- calls new functions in the main plot generation script `plot_aggregate_loanbooks.R`
NOTE
- once we have a clearer view of the P4S product, this function may need to be moved to a package and exported
- in that case it would likely undergo further visual improvements
> plot net aggregate alignment by financial exposure

- README.md
`pak::pak` now seems to be preferred over `devtools::install_github` by `tidyverse` et al:
https://github.com/tidyverse/dplyr/blob/d69802224a1df16d7a795ce313880116ea62ed6e/README.md
> nit: modernize `README.md` instructions

- run_aggregate_loanbooks.R
- run_pacta_in_bulk.R
closes #74 
- running PACTA `target_market_share()` calculation handles missing values in `production` column: https://github.com/RMI-PACTA/r2dii.analysis/pull/460
- removes manual replacement of `NA`s for `production` in `abcd`, when `target_market_share()` is applied:
- `run_pacta_in_bulk.R`
- `run_aggregate_loanbooks.R`
> rm superfluous handling of NAs in abcd when PACTA is run

- run_aggregate_loanbooks.R
- run_pacta_in_bulk.R
closes ADO https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/10031
- Syncs across workflows:
- `run_pacta_in_bulk.R` gains a section that adds a `meta_loanbook`
- it subsequently processes this `meta_loanbook` like any other loan book and returns the corresponding results
- `run_aggregate_loanbooks.R` gains meta loan book analysis as well to ensure that standard PACTA and aggregate analysis remain in sync
> Return meta loanbook

- R/functions_prep_project.R
- README.md
- plot_aggregate_loanbooks.R
- prep_sample_loanbook_raw.R
- run_aggregate_loanbooks.R
- run_pacta_in_bulk.R
closes #82 
- all references of `pacta.aggregate.loanbook.plots` change to `pacta.multi.loanbook.analysis`
> switch to package pacta.multi.loanbook.analysis

- R/functions_prep_project.R
closes #90 
- replaces `max(code_level)` with `max(nchar(code))` to identify sector codes at the most granular level, as code_level was deprecated from `r2dii.data`
> replace code_level with nchar
